name: CI Luacheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Luacheck
        run: sudo apt update && sudo apt install luarocks -y && luarocks install luacheck

      - name: Run luacheck of dotfiles/.config/nvim/init.lua
        run: luacheck dotfiles/.config/nvim/init.lua

      - name: Run luacheck of dotfiles/.config/nvim/lua/plugins.lua
        run: luacheck dotfiles/.config/nvim/lua/plugins.lua
