---
name: CI Luacheck

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:  # manual workflow run from Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Luacheck
        run: sudo apt update && sudo apt install luarocks -y && sudo luarocks install luacheck

      - name: Run luacheck of dotfiles/.config/nvim/init.lua
        run: luacheck dotfiles/.config/nvim/init.lua

      - name: Run luacheck of dotfiles/.config/nvim/lua/plugins.lua
        run: luacheck dotfiles/.config/nvim/lua/plugins.lua
